/**
 * Fills src/lib/data/hero-manifest.ts from real, already-rights-filtered NPS
 * API images (src/lib/nps.ts -> fetchParkImages) whose real dimensions were
 * already probed into image-dims.json (npm run probe-images). Picks the
 * widest 4K+ (>=3840px), hero-safe-aspect (1.3-2.1) image per park. Never
 * invents a URL — every entry here was actually fetched and measured.
 *
 * Usage: npm run pick-hero-manifest
 */
import { writeFileSync } from "node:fs";
import { ALL_PARKS_MINI } from "../src/lib/data/all-parks-mini";
import { fetchParkImages } from "../src/lib/nps";
import dims from "../src/lib/data/image-dims.json";

const DIMS = dims as Record<string, { width: number; height: number }>;
const MIN_WIDTH = 3840;
const ASPECT_RANGE: [number, number] = [1.3, 2.1];

interface Entry {
  url: string;
  credit: string;
  alt: string;
}

async function main() {
  const picks: Record<string, Entry> = {};
  let done = 0;

  for (const park of ALL_PARKS_MINI) {
    done++;
    process.stdout.write(`[${done}/${ALL_PARKS_MINI.length}] ${park.code}... `);
    const images = await fetchParkImages(park.code);
    const candidates = images
      .map((im) => ({ im, d: DIMS[im.url] }))
      .filter(({ d }) => d && d.width >= MIN_WIDTH && d.width / d.height >= ASPECT_RANGE[0] && d.width / d.height <= ASPECT_RANGE[1])
      .sort((a, b) => b.d.width - a.d.width);

    if (candidates.length === 0) {
      console.log("no qualifying 4K image");
      continue;
    }
    const best = candidates[0];
    picks[park.code] = { url: best.im.url, credit: best.im.credit, alt: best.im.altText || park.name };
    console.log(`${best.d.width}x${best.d.height}`);
  }

  const body = Object.entries(picks)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([code, e]) => `  ${code}: ${JSON.stringify(e)},`)
    .join("\n");

  const out = `export interface HeroManifestEntry {
  url: string;
  credit: string;
  alt: string;
}

/**
 * Hand-picked hero images (production brief T4) — real NPS Data API images,
 * rights-filtered (fetchParkImages already excludes anything not credited to
 * NPS/National Park Service), selected for real probed width >=${MIN_WIDTH}px and a
 * hero-safe aspect ratio. Generated by \`npm run pick-hero-manifest\` from
 * src/lib/data/image-dims.json — never a hand-typed or invented URL. ${Object.keys(picks).length}/${ALL_PARKS_MINI.length}
 * parks had a qualifying image at probe time; the rest fall back to the
 * size-aware NPS-API selection already in image-select.ts.
 */
export const HERO_MANIFEST: Record<string, HeroManifestEntry> = {
${body}
};
`;

  writeFileSync(new URL("../src/lib/data/hero-manifest.ts", import.meta.url), out);
  console.log(`\nWrote ${Object.keys(picks).length} entries to hero-manifest.ts`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
