export interface HeroManifestEntry {
  url: string;
  credit: string;
  alt: string;
}

/**
 * Hand-picked hero images (production brief T4) — real NPS Data API images,
 * rights-filtered (fetchParkImages already excludes anything not credited to
 * NPS/National Park Service), selected for real probed width >=3840px and a
 * hero-safe aspect ratio. Generated by `npm run pick-hero-manifest` from
 * src/lib/data/image-dims.json — never a hand-typed or invented URL. 43/63
 * parks had a qualifying image at probe time; the rest fall back to the
 * size-aware NPS-API selection already in image-select.ts.
 */
export const HERO_MANIFEST: Record<string, HeroManifestEntry> = {
  acad: {"url":"https://www.nps.gov/common/uploads/structured_data/D4EA2DD2-C4B9-9CB4-75DB3AB73C80F432.jpg","credit":"NPS Photo by Kent Miller","alt":"While seated on a blanket on a patch of mountaintop granite, a man and woman clasp their arms around"},
  arch: {"url":"https://www.nps.gov/common/uploads/structured_data/3C7A0C49-1DD8-B71B-0B460D58D6E83B40.jpg","credit":"NPS/Wonderly","alt":"the Milky Way arcs above silhouetted stone pinnacles"},
  badl: {"url":"https://www.nps.gov/common/uploads/structured_data/3C82EBFE-1DD8-B71B-0B21072718DB2A95.jpg","credit":"NPS Photo","alt":"Badlands formations are very rugged and often have sharp peaks."},
  bibe: {"url":"https://www.nps.gov/common/uploads/structured_data/8BCD073D-D2AF-C63C-F75A21DF9E355C61.jpg","credit":"NPS / C. Negele","alt":"Century Plant Agave"},
  bisc: {"url":"https://www.nps.gov/common/uploads/structured_data/3C870833-1DD8-B71B-0BE93D49E0DF6503.jpg","credit":"NPS photo","alt":"The coral reefs are located mostly on the Eastern side of the park."},
  brca: {"url":"https://www.nps.gov/common/uploads/structured_data/61F08520-E14F-18F2-BF5F3D89482631BD.jpg","credit":"NPS Photo / Peter Densmore","alt":"A red rock landscape and plateau forest glows with the morning sun"},
  cany: {"url":"https://www.nps.gov/common/uploads/structured_data/D0AD44B0-0857-0A5D-0C5E18ED27D08813.jpg","credit":"NPS/Rhodes Smartt","alt":"A windy steep dirt road leads up the side of a sandstone cliff. River in background."},
  cave: {"url":"https://www.nps.gov/common/uploads/structured_data/2B40AD3D-DDDB-2F2E-1CB524F96FF08C4B.jpg","credit":"NPS / Eymard Bangcoro","alt":"Photo of the Natural Entrance to Carlsbad Cavern with visitors hiking down the trail."},
  cuva: {"url":"https://www.nps.gov/common/uploads/structured_data/F7425874-D97F-BFD6-36581A36C8A7FF0D.jpg","credit":"NPS Photo / D.J. Reiser","alt":"People in bright orange kayaks paddle around a bend in a river, past green trees and a rocky shore."},
  dena: {"url":"https://www.nps.gov/common/uploads/structured_data/FC7B6DBE-B7A8-DC59-246E01A289DBF21E.jpg","credit":"NPS Photo / Emily Mesner","alt":"light turns a snowy mountain shades of pink and purple"},
  drto: {"url":"https://www.nps.gov/common/uploads/structured_data/3C810049-1DD8-B71B-0B0040641619D4A6.jpg","credit":"NPS Photo / Maria Belen Farias","alt":"A view of Fort Jefferson from the moat all."},
  glba: {"url":"https://www.nps.gov/common/uploads/structured_data/3C790BBF-1DD8-B71B-0B0AE92D0B9C24EB.jpg","credit":"NPS Photo","alt":"Icebergs, calved from tidewater glaciers are a common sight in Glacier Bay National Park."},
  grba: {"url":"https://www.nps.gov/common/uploads/structured_data/7B044BE0-C96F-A30E-546520529A456B57.jpg","credit":"NPS Photo","alt":"Tan and green Visitor center with mountains in the background."},
  grsa: {"url":"https://www.nps.gov/common/uploads/structured_data/B841835F-9E6C-AB24-2A2DCCD0200F302B.jpg","credit":"NPS/Patrick Myers","alt":"Gold cottonwood trees, large dunes, a silver cloud, and snow-capped mountain"},
  grte: {"url":"https://www.nps.gov/common/uploads/structured_data/77090CDC-C6C0-0602-DBAF603A69CFD10D.jpg","credit":"NPS Photo/Adams","alt":"A mama grizzly standing up with a cub at her side"},
  gumo: {"url":"https://www.nps.gov/common/uploads/structured_data/AC3F41C8-CB05-1F59-18AFF80496BA94D1.jpg","credit":"NPS/K/ Poteet","alt":"A metal and stone entrance sign stands in front of a building and desert mountains"},
  havo: {"url":"https://www.nps.gov/common/uploads/structured_data/C5AEDF53-AE4A-F6DB-2FBA7BE158386C0E.jpg","credit":"NPS Photo/J. Wei","alt":"A cloud-filled volcanic crater at sunrise with a mountain rising behind"},
  hosp: {"url":"https://www.nps.gov/common/uploads/structured_data/243E69E8-B5AB-6E14-DDD7BF3A6FEFE437.jpg","credit":"NPS photo Mark David Artist In Residence 2015","alt":"Stone bridge surrounded by brilliant yellow and green leaves"},
  indu: {"url":"https://www.nps.gov/common/uploads/structured_data/9253EDFB-AAFD-E111-B985CD2747F5C48F.jpg","credit":"NPS Photo","alt":"Michigan Lake beach with green grassy dunes in the background, under a blue sky."},
  isro: {"url":"https://www.nps.gov/common/uploads/structured_data/3C7AC355-1DD8-B71B-0B9C2F07853F39F1.jpg","credit":"NPS Photo / Paul Brown","alt":"Aerial View of Belle Harbor"},
  jeff: {"url":"https://www.nps.gov/common/uploads/structured_data/A6BB26F2-E35A-F940-E65C458BC5784713.jpg","credit":"NPS Photo/Sue Ford","alt":"looking up at the curve of the Gateway Arch against the sky"},
  jotr: {"url":"https://www.nps.gov/common/uploads/structured_data/3C85EF02-1DD8-B71B-0B467F2B5F7483AC.jpg","credit":"NPS/Brad Sutton","alt":"Joshua trees grow on a flat plain with boulder outcrops and mountains in the distance"},
  katm: {"url":"https://www.nps.gov/common/uploads/structured_data/3C7A0FDB-1DD8-B71B-0B8933ACA92FE6B3.jpg","credit":"NPS/David Jacob","alt":"salmon jumping at waterfall"},
  kefj: {"url":"https://www.nps.gov/common/uploads/structured_data/6F2AB13B-A9A4-ABE2-E74F8E73914A44B4.jpg","credit":"NPS Photo","alt":"A person looks out over a view of snow, ice, and mountain peaks"},
  kova: {"url":"https://www.nps.gov/common/uploads/structured_data/9B843EAB-BE9D-AF8A-7D23CF259CD9FCB9.jpg","credit":"NPS Photo / Amy Martin (2022 Artist in Residence)","alt":"Dark skies shadow the horizon. A rainbow is illuminated above Niaktovik Creek"},
  lavo: {"url":"https://www.nps.gov/common/uploads/structured_data/3C8739BB-1DD8-B71B-0B8336A925B1A6C7.jpg","credit":"NPS Photo / Amanda Sweeney","alt":"Golden grasses edge a pond reflecting a snow-dusted peak"},
  maca: {"url":"https://www.nps.gov/common/uploads/structured_data/0DB94E27-0FF0-E98D-2F0AA9F8B4800869.jpg","credit":"NPS Photo / J. Cooper","alt":"Looking out from a large cave entrance with falling water and green trees shown over the entrance."},
  mora: {"url":"https://www.nps.gov/common/uploads/structured_data/3C7C6A93-1DD8-B71B-0BA75B16C5FA3690.jpeg","credit":"NPS Photo/ K. Loving","alt":"Purple lupine and white bistort bloom in a meadow alongside a sign for the Wonderland Trail."},
  noca: {"url":"https://www.nps.gov/common/uploads/structured_data/3C7A5FF6-1DD8-B71B-0BAAFB88D0A3DC08.jpg","credit":"NPS Photo/T. Baldwin","alt":"Jagged mountain peaks give way to glaciers."},
  npsa: {"url":"https://www.nps.gov/common/uploads/structured_data/3C84F643-1DD8-B71B-0BC6F3EA2E1F58AB.jpg","credit":"NPS Photo / Michael Larson","alt":"Tuafanua Trail"},
  pefo: {"url":"https://www.nps.gov/common/uploads/structured_data/3C85B554-1DD8-B71B-0BA79402AD7E7711.jpg","credit":"NPS Photo","alt":"Two visitors walk the Blue Mesa Trail between blue, purple, and grey badlands."},
  pinn: {"url":"https://www.nps.gov/common/uploads/structured_data/9CCA8ED3-ABB9-CB69-EF4B32F2ADACEC47.jpeg","credit":"NPS Photo/ Katherine Fielding","alt":"A massive rock spire with California condors flying above the peak."},
  redw: {"url":"https://www.nps.gov/common/uploads/structured_data/13E30047-1DD8-B71B-0B03D2E0CECCE8AD.jpg","credit":"NPS Photo / John Chao","alt":"Visitors chatting with a ranger above a river mouth."},
  romo: {"url":"https://www.nps.gov/common/uploads/structured_data/0772DCB5-BDCF-0571-AEE80FA1F2590755.jpg","credit":"NPS Photo/R.Williams","alt":"Alpine wildflowers are blooming"},
  sagu: {"url":"https://www.nps.gov/common/uploads/structured_data/5CB8B2F6-01B7-9A50-73702A355E4136B8.jpg","credit":"NPS Photo","alt":"Saguaro flowers"},
  shen: {"url":"https://www.nps.gov/common/uploads/structured_data/3C80B867-1DD8-B71B-0B328321E4420769.jpg","credit":"NPS Photo / Neal Lewis","alt":"A road surrounded by fall foliage turns a curve around a small waterfall."},
  thro: {"url":"https://www.nps.gov/common/uploads/structured_data/3C793AD5-1DD8-B71B-0B4A3C1BFA5B4C83.jpg","credit":"NPS Photo / Mark Meyers","alt":"A colorfully striped butte in the foreground overlooks a dark green badlands landscape"},
  voya: {"url":"https://www.nps.gov/common/uploads/structured_data/31EDB5D6-FA28-880B-80068EB62E6C86CC.jpg","credit":"NPS Photo / Daniel Dendler","alt":"Photograph of northern lights over a lake."},
  whsa: {"url":"https://www.nps.gov/common/uploads/structured_data/3C7FE53E-1DD8-B71B-0BE4AEBECAB602AD.jpg","credit":"NPS Photo","alt":"Aerial of white sand dunes."},
  wica: {"url":"https://www.nps.gov/common/uploads/structured_data/3C7AD1AD-1DD8-B71B-0B7C9E1C79DA6F5C.jpg","credit":"NPS Photo","alt":"a caver with pads and helmet crawling in the cave"},
  wrst: {"url":"https://www.nps.gov/common/uploads/structured_data/3C7AB124-1DD8-B71B-0B224A3B96A7304E.jpg","credit":"NPS Photo/ Matthew Yarbrough","alt":"Historic, large, red buildings with mountains in the background"},
  yell: {"url":"https://www.nps.gov/common/uploads/structured_data/2815637A-9869-FC9C-99461D0B36AA1922.jpg","credit":"NPS / Jacob W. Frank","alt":"The sun sets behind the sharp point of a snow-covered mountain; pink clouds are reflected in a pond"},
  yose: {"url":"https://www.nps.gov/common/uploads/structured_data/3C84C6CF-1DD8-B71B-0B1C7CB883AA8FB1.jpg","credit":"NPS / Bob Roney","alt":"A rainbow over a mountain in the distance."},
};
